import type { Course, Enrollment } from "./types"

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Data Structures and Algorithms",
    code: "CS-301",
    description:
      "Comprehensive study of fundamental data structures and algorithms including arrays, linked lists, trees, graphs, sorting, and searching algorithms.",
    credits: 4,
    lecturer: {
      id: "2",
      name: "Dr. Sarah Johnson",
      email: "lecturer@university.edu",
      avatar: "/lecturer-avatar.jpg",
    },
    syllabus: {
      filename: "CS301_Syllabus_Fall2024.pdf",
      url: "/placeholder.pdf",
      uploadedAt: "2024-08-15T10:00:00Z",
    },
    schedule: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "10:00 AM - 11:00 AM",
      room: "Room 201",
    },
    capacity: 50,
    enrolled: 45,
    status: "active",
    semester: "Fall",
    year: 2024,
    createdAt: "2024-08-01T09:00:00Z",
    updatedAt: "2024-08-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Advanced Mathematics",
    code: "MATH-401",
    description:
      "Advanced topics in calculus, linear algebra, and differential equations with applications in computer science and engineering.",
    credits: 3,
    lecturer: {
      id: "4",
      name: "Dr. Emily Davis",
      email: "emily.davis@university.edu",
      avatar: "/placeholder.svg?key=emily",
    },
    schedule: {
      days: ["Tuesday", "Thursday"],
      time: "2:00 PM - 3:30 PM",
      room: "Room 105",
    },
    capacity: 30,
    enrolled: 28,
    status: "active",
    semester: "Fall",
    year: 2024,
    createdAt: "2024-07-20T14:00:00Z",
    updatedAt: "2024-08-10T16:00:00Z",
  },
  {
    id: "3",
    title: "Computer Networks",
    code: "CS-402",
    description:
      "Study of computer network protocols, architecture, and implementation including TCP/IP, routing, and network security.",
    credits: 3,
    lecturer: {
      id: "2",
      name: "Dr. Sarah Johnson",
      email: "lecturer@university.edu",
      avatar: "/lecturer-avatar.jpg",
    },
    syllabus: {
      filename: "CS402_Syllabus_Fall2024.pdf",
      url: "/placeholder.pdf",
      uploadedAt: "2024-08-12T14:30:00Z",
    },
    schedule: {
      days: ["Monday", "Wednesday"],
      time: "1:00 PM - 2:30 PM",
      room: "Room 301",
    },
    capacity: 40,
    enrolled: 38,
    status: "active",
    semester: "Fall",
    year: 2024,
    createdAt: "2024-07-25T11:00:00Z",
    updatedAt: "2024-08-12T14:30:00Z",
  },
  {
    id: "4",
    title: "Database Systems",
    code: "CS-350",
    description: "Introduction to database design, SQL, normalization, and database management systems.",
    credits: 3,
    lecturer: {
      id: "5",
      name: "Dr. Michael Chen",
      email: "michael.chen@university.edu",
      avatar: "/placeholder.svg?key=michael",
    },
    schedule: {
      days: ["Tuesday", "Thursday"],
      time: "11:00 AM - 12:30 PM",
      room: "Room 250",
    },
    capacity: 35,
    enrolled: 32,
    status: "active",
    semester: "Fall",
    year: 2024,
    createdAt: "2024-07-30T10:00:00Z",
    updatedAt: "2024-08-05T15:00:00Z",
  },
  {
    id: "5",
    title: "Physics Laboratory",
    code: "PHYS-201",
    description: "Hands-on laboratory experiments in mechanics, thermodynamics, and electromagnetism.",
    credits: 2,
    lecturer: {
      id: "4",
      name: "Dr. Emily Davis",
      email: "emily.davis@university.edu",
      avatar: "/placeholder.svg?key=emily",
    },
    schedule: {
      days: ["Friday"],
      time: "2:00 PM - 5:00 PM",
      room: "Physics Lab A",
    },
    capacity: 20,
    enrolled: 18,
    status: "active",
    semester: "Fall",
    year: 2024,
    createdAt: "2024-08-05T13:00:00Z",
    updatedAt: "2024-08-08T09:00:00Z",
  },
]

export const mockEnrollments: Enrollment[] = [
  {
    id: "1",
    studentId: "3",
    courseId: "1",
    status: "approved",
    enrolledAt: "2024-08-20T10:00:00Z",
    approvedAt: "2024-08-20T14:00:00Z",
    approvedBy: "1",
  },
  {
    id: "2",
    studentId: "3",
    courseId: "2",
    status: "approved",
    enrolledAt: "2024-08-21T09:00:00Z",
    approvedAt: "2024-08-21T11:00:00Z",
    approvedBy: "1",
  },
  {
    id: "3",
    studentId: "6",
    courseId: "1",
    status: "pending",
    enrolledAt: "2024-08-25T15:30:00Z",
  },
  {
    id: "4",
    studentId: "7",
    courseId: "3",
    status: "pending",
    enrolledAt: "2024-08-26T11:20:00Z",
  },
]
